### ISSUE TITLE
can't edit; login link gives auth error

### ISSUE THREAD

**Issue by scruss** [Telenav/improveosm.org#2] opened 2016-09-08 18:43 UTC
"Login with OSM" link gives blank popup window and an "Authentication Error" notice on the improveosm map

**Comment by mvexel** [comment] 2016-09-08 22:23
@scruss This may have to do with having HTTPS Anywhere or a similar extension enabled. I had the same problem and unselecting openstreetmap.org fixed it for me.

<img width="338" alt="screenshot 2016-09-08 16 23 18" src="https://cloud.githubusercontent.com/assets/120452/18369058/94bb731c-75e0-11e6-8358-9e393d174e77.png">

**Comment by scruss** [comment] 2016-09-08 22:56
Good to know. I guess it's a hard limitation, as other osm auth sites don't give me that issue

**Comment by mvexel** [comment] 2016-09-09 14:24
I don't think it is actually, so I will leave this open for us to see if we can fix.

**Comment by tudorg-telenav** [comment] 2016-11-17 17:18
changed `id.js` to cleanly force `https`
by "cleanly" I mean that the `Connection` object constructor was already implemented as to accept enforcing of `https`
closing the issue

**Comment by scruss** [comment] 2016-11-17 18:06
still fails, sorry; firefox 49.02 (ubuntu)

**Comment by tudorg-telenav** [comment] 2016-11-17 20:07
thank you, I will further investigate

**Comment by tudorg-telenav** [comment] 2016-11-22 14:19
@scruss is there any chance you didn't clear the browser's cache? the file modified for this is not versioned
(at this point no minification is done for the production deploy) At this point the few files changed are versioned. Please try clearing the browser's cache, and if it works then, I will version this file too

**Comment by tudorg-telenav** [comment] 2016-12-28 09:57
some time has passed, and still, I cannot reproduce this, even in FF
until further notices, I'll close it

**Closed by tudorg-telenav** 2016-12-28 09:57 UTC
